ATM-Consulting/dolibarr_module_externalaccess

langs/fr_FR/externalaccess.lang, www/class/context.class.php, www/lib/externalaccess.lib.php, www/tpl/errors.tpl.php, www/tpl/header.tpl.php
Fix nom de fonction pendant qu'il en est encore temps
New navbar aussi si on veut mettre un lien du style retour en arrière ou des bouton d'ajout d'élément
=> New show errors

www/class/context.class.php, www/css/creative.css.php, www/js/creative.js, www/lib/externalaccess.lib.php, www/tpl/footer.tpl.php, www/tpl/header.tpl.php
need https://github.com/ATM-Consulting/dolibarr_module_externalaccess/pull/4
=> New iframe support

admin/externalaccess_setup.php, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, lib/externalaccess.lib.php, www/tpl/menu.tpl.php, www/tpl/services.tpl.php
hier, j'ai trouvé du code non comité sur mon disque pour gérer les expeditions... du coup j'ai fait en sorte que ça fonctionne...voilà... je me disais bien que j'avais dev les expéditions ... #jaipasdetete
=> New expeditions support

www/css/creative.css.php, www/js/creative.js
prend en compte les appels de type iframe aussi
=> Add smooth scroll + offset

admin/externalaccess_setup.php, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, lib/externalaccess.lib.php, www/tpl/menu.tpl.php, www/tpl/services.tpl.php
Affichage des tickets liés à la société
=> New : work with ticket module

admin/externalaccess_setup.php, langs/fr_FR/externalaccess.lang
=> New conf wysiwyg + improvments (master)

lib/externalaccess.lib.php
Fix an issue that show all documents available in DOLIBARR when Multicompany module activated.
Now, it will show only the documents created by the Portal owner company.
=> Add compatibility with Multicompany Module

class/actions_externalaccess.class.php, langs/fr_FR/externalticket.lang, lib/ticket.lib.php
=> Fix private msg, msg sort order, secure message access

lib/ticket.lib.php
Reste à permettre de cliquer sur les liens pour les voir mais au moins on voit la liste des fichiers que l'on a envoyé
=> Add ticket file list on ticket message

core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
#FIX tables ordering
The tables were ordered by ref asc by default.
The sql requests were ordered by date DESC which is logical but not implemented on list rendering.
That's done now.
=> fix dataTable order

class/actions_externalaccess.class.php, langs/fr_FR/externalticket.lang, lib/ticket.lib.php
- Fix missing event messages
- Fix wrong id
- Fix rights tests
=> FIX : right tests and messages

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/ticket.lib.php
Ajout du tri par défaut sur la date de création du ticket
=> NEW : Ticket list order on date

ChangeLog.md, core/modules/modexternalaccess.class.php
Modify ChangeLog and version number
=> FIX/Modify ChangeLog & version number

lib/ticket.lib.php
Add nl2br to skip a line between comment and "attached files"
=> Fix display concatenation behaviour

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
=> NEW Hooks for queries

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
Ajout hook "listColumnField" pour l'affichage des colonnes de la liste des expéditions
=> New - Hook for list delivery

ChangeLog.md, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, lib/externalaccess.lib.php, www/css/creative.css.php, www/js/creative.js, www/tpl/menu.tpl.php
Regroupement des menus actuels sous de nouveau menus : Administratif / Technique / Formation
Option d'affichage du regroupement si + de X menus affichés
Gestion de l'affichage responsive
note : 
- Ce système est rétrocompatible avec les modules qui ajoutent des entrées au menu.
- Sur le changelog j'ai retiré les crochés car en markdown c'est utilisé pour les images et url donc j'ai fait le correctif
=> NEW : Top menu group possibility

ChangeLog.md, core/modules/modexternalaccess.class.php, www/lib/externalaccess.lib.php
V13 compatibility after renaming object livraison into delivery
=> Fix/V13 Compatibility

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php
- FIX : V13 compatibility for user socid *2021-03-24* - 1.13.2
=> FIX : V13 compatibility for user socid

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php
See https://github.com/ATM-Consulting/dolibarr_module_externalaccess/pull/57
=> PULLUP : FIX : V13 compatibility for user socid

ChangeLog.md, admin/externalaccess_setup.php, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, www/tpl/header.tpl.php
=> NEW : Option to set favicon

lib/externalaccess.lib.php
FIX : download link was appearing even if file doesn't exist if $object->last_main_doc is not NULL
=> test if file is readable

lib/externalaccess.lib.php
FIX : download link was appearing even if file doesn't exist if $object->last_main_doc is not NULL
=> PULL UP : test if file is readable

ChangeLog.md, core/modules/modexternalaccess.class.php, www/css/creative.css.php, www/script/interface.php
Compatibility V13 : add token renowal
=> FIX : add token renowal

ChangeLog.md, core/modules/modexternalaccess.class.php
- editor_name = 'ATM Consulting'
- editor_url = "https://www.atm-consulting.fr"
- family = 'ATM Consulting – Autres'
=> FIX : Compatibility V14 - Modify descriptor informations

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
Correction of the path when there is a "/" in the reference of a shipment
=> FIX : External access shipment download link

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
Remontée du fix : Correction of the path when there is a "/" in the reference of a shipment
[https://github.com/ATM-Consulting/dolibarr_module_externalaccess/pull/75](url)
=> PULLUP : FIX Shipment dowload link externalaccess

ChangeLog.md, lib/externalaccess.lib.php
Remontée du fix : Correction of the path when there is a "/" in the reference of a shipment
[https://github.com/ATM-Consulting/dolibarr_module_externalaccess/pull/75](url)
=> PULLUP : FIX Shipment dowload externalaccess

ChangeLog.md, lib/externalaccess.lib.php
Correction of the path when there is a "/" in the reference of a shipment
[https://github.com/ATM-Consulting/dolibarr_module_externalaccess/pull/75](url)
=> PULLUP : External access shipment download link

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php
=> Fix : add contact to ticket on creation

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php, lib/ticket.lib.php, www/class/context.class.php, www/controllers/tickets.controller.php
J'ai ajouté 2 hooks et j'ai déplacé la liste des tickets sur le systeme de controllers
=> NEW : Add hook for ticket's card && Move tickets list to new CONTROLLER SYSTEM

admin/externalaccess_setup.php, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, www/class/context.class.php, www/controllers/projects.controller.php, www/controllers/tasks.controller.php, www/tpl/menu.tpl.php
1 - All modified files are now PHP CS Dolibarr ruleset compliant (dolibarr branch version 13.0)
2 - Update project controller to make it like expedition display only project where user logged is contact of the projet
3 - Add Task controller and view
=> NEW : Task Management

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php
=> PULL UP : Fix contact id (important pour le support client)

ChangeLog.md, core/modules/modexternalaccess.class.php, www/controllers/supplier_invoices.controller.php
oubli de la colonne ref fournisseur
=> FIX : ref_suppliar column

ChangeLog.md, admin/externalaccess_setup.php, core/modules/modexternalaccess.class.php, langs/fr_FR/externalaccess.lang, www/controllers/expeditions.controller.php
Gestion des Extrafields d'expédition sur la liste des BL
=> NEW T3121 Print Extrafields on shipping list

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modexternalaccess.class.php, lib/ticket.lib.php, www/controllers/default.controller.php, www/controllers/propals.controller.php, www/controllers/tickets.controller.php, www/tpl/menu.tpl.php
Permissions employé et ajout d'un hook pour la permission d'ajouter un message à un ticket
=> NEW : Permissions employee et ajout message ticket

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
Gestion des selects par la fonction stdFormHelper
=> stdFormHelper add select

ChangeLog.md, core/modules/modexternalaccess.class.php, www/controllers/propals.controller.php
Ajout de 2 Hook qui permettent d'ajouter une colonne dans la liste des propals
=> New add hooks propals controller

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php
Ajouter la possibilité d'afficher un input de type "checkbox"
J'ai ajouté un "elseif" car la donnée "value" dans l'input classique rentre en conflit avec le type "checkbox"
=> Ajout type checkbox dans la fonction "stdFormHelper"

admin/externalaccess_setup.php, class/actions_externalaccess.class.php, langs/fr_FR/externalaccess.lang
Ajout d'une conf permettant, lors de son activation, de reset la valeur prise par la variable "last_main_doc" évitant ainsi les "conflits" lors du téléchargement de document : 
Lorsque l'on peut télécharger plusieurs document différent depuis une même page du portail (propal par exemple), le document téléchargé par le lien de l'objet est le dernier ayant été généré, et donc pas toujours le bon
=> NEW : Ajout d'une configuration

ChangeLog.md, core/modules/modexternalaccess.class.php, www/class/controller.class.php, www/controllers/default.controller.php, www/controllers/expeditions.controller.php, www/controllers/forgotten_password.controller.php, www/controllers/invoices.controller.php, www/controllers/orders.controller.php, www/controllers/personalinformations.controller.php, www/controllers/projects.controller.php, www/controllers/propals.controller.php, www/controllers/supplier_invoices.controller.php, www/controllers/tasks.controller.php, www/controllers/tickets.controller.php, www/main.inc.php
Problème de gestion des droits utilisateurs.
solution déplacement des test des droits utilisateurs dans la méthode prévue à cet effet
=> FIX : User access rights

ChangeLog.md, core/modules/modexternalaccess.class.php, www/class/controller.class.php, www/controllers/default.controller.php, www/controllers/expeditions.controller.php, www/controllers/forgotten_password.controller.php, www/controllers/invoices.controller.php, www/controllers/orders.controller.php, www/controllers/personalinformations.controller.php, www/controllers/projects.controller.php, www/controllers/propals.controller.php, www/controllers/supplier_invoices.controller.php, www/controllers/tasks.controller.php, www/controllers/tickets.controller.php, www/main.inc.php
=> PULLUP : FIX : User access rights

ChangeLog.md, core/modules/modexternalaccess.class.php, www/controllers/expeditions.controller.php, www/controllers/invoices.controller.php, www/controllers/orders.controller.php, www/controllers/propals.controller.php, www/tpl/menu.tpl.php
=> FIX : Missing check for module activation

ChangeLog.md, admin/externalaccess_setup.php, class/actions_externalaccess.class.php, class/html.formexternal.class.php, core/modules/modexternalaccess.class.php, lib/externalaccess.lib.php, lib/ticket.lib.php, www/class/context.class.php, www/class/controller.class.php, www/class/user_external_access.class.php, www/controllers/expeditions.controller.php, www/controllers/forgotten_password.controller.php, www/controllers/invoices.controller.php, www/controllers/orders.controller.php, www/controllers/personalinformations.controller.php, www/controllers/projects.controller.php, www/controllers/propals.controller.php, www/controllers/supplier_invoices.controller.php, www/controllers/tasks.controller.php, www/controllers/tickets.controller.php, www/lib/externalaccess.lib.php, www/tpl/form.forgotten_password.tpl.php, www/tpl/form.login.tpl.php, www/tpl/header.tpl.php, www/tpl/menu.tpl.php, www/tpl/services.tpl.php, www/tpl/userinfos.tpl.php
le but est de préparer pour une gestion multi entité et surtout permettre à un module de ne pas avoir à instancier la classe context qui justement utilise le "context" courant de l'utilisateur courant et donc les liens générés sont lié à l'utilisateur alors que potentiellement lors de la génération du lien on est sur Dolibarr et pas le portail
=> NEW : factoring

www/lib/login.lib.php, www/tpl/form.login.tpl.php
As in Dolibarr, when multicompany is active, a select input is shown in login page so as to login in the right one
=> Select company on login page

www/main.inc.php
Reverts ATM-Consulting/dolibarr_module_externalaccess#164
=> Revert "Fix:CSRF Token is regenerated before test"

ChangeLog.md, core/modules/modExternalAccess.class.php, www/class/context.class.php
=> PULLUP : FIX Fatal php 8.2 compatibility

ChangeLog.md, core/modules/modexternalaccess.class.php, lib/ticket.lib.php, www/controllers/tickets.controller.php
=> FIX : DA025305 - Extrafields tickets non-affichés

ChangeLog.md, class/actions_externalaccess.class.php, core/modules/modExternalAccess.class.php
- add hook for contact mail pour le module "smart customer support"
=> NEW : add hook for contact mail
